swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST UI
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /v1/{author_name}:
    get:
      parameters:
        - in: path
          name: author_name
          required: true
          type: "string"
          description: Author name
      operationId: "author.get_author_information"
      tags:
        - "Author"
      summary: "The author data based on author name"
      description: "Get author information based on author name"
      responses:
        200:
          description: "Successful author information"
          schema:
            type: "object"
            items:
              properties:
                author_name:
                  type: "string"
                author_articles_published:
                  type: "object"
                coauthors_name_list:
                    type: "object"
                author_community:
                    type: "object"

  /v1/author:
    get:
      operationId: "author.read_author"
      tags:
        - "Author"
      summary: "The author data structure supported by the server application"
      description: "Read the authors' information"
      responses:
        200:
          description: "Successful read authors' list operation"
          schema:
            type: "array"
            items:
              properties:
                author_name:
                  type: "string"
                author_articles_published:
                  type: "string"
                coauthors_name_list:
                  type: "string"
                date:
                  type: "string"
                author_community:
                  type: "string"